trigger:
- main

pool:
  vmImage: ubuntu-latest
steps:

- task: Docker@2
  inputs:
    containerRegistry: 'bootstrapapp'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
- task: HelmDeploy@0
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceConnection: 'boot-aks-default'
    namespace: 'default'
    command: 'upgrade'
    chartType: 'FilePath'
    chartPath: 'my-aks-charts'
    releaseName: 'bootsrap'